import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { adminFetch } from "../utils/adminApi";

const AdminInventory = () => {
  const [products, setProducts] = useState([]); const [threshold, setThreshold] = useState(5); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { try { setLoading(true); const response = await adminFetch(`/admin/inventory/low-stock?threshold=${threshold}`); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to load inventory."); setProducts(data.products || []); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  useEffect(() => {
    const loadInitialInventory = async () => { try { setLoading(true); const response = await adminFetch("/admin/inventory/low-stock?threshold=5"); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to load inventory."); setProducts(data.products || []); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
    loadInitialInventory();
  }, []);
  return <main className="container py-5"><div className="d-flex justify-content-between align-items-center mb-4"><div><p className="text-muted mb-1">Admin operations</p><h1 className="h2 fw-bold mb-0">Low-stock inventory</h1></div><Link to="/admin" className="btn btn-outline-dark">Dashboard</Link></div><div className="d-flex gap-2 align-items-center mb-3"><label htmlFor="threshold" className="fw-semibold">Show stock at or below</label><input id="threshold" className="form-control" type="number" min="0" max="100" value={threshold} onChange={(event) => setThreshold(event.target.value)} style={{ maxWidth: 100 }} /><button className="btn btn-dark" onClick={load}>Apply</button></div>{error && <div className="alert alert-danger">{error}</div>}<div className="card border-0 shadow-sm"><div className="table-responsive"><table className="table table-hover align-middle mb-0"><thead className="table-dark"><tr><th>Product</th><th>Category</th><th className="text-end">Price</th><th className="text-end">Stock</th><th></th></tr></thead><tbody>{loading ? <tr><td colSpan="5" className="text-center py-5">Loading inventory...</td></tr> : products.length === 0 ? <tr><td colSpan="5" className="text-center py-5">No low-stock products.</td></tr> : products.map((product) => <tr key={product.id}><td><strong>{product.company}</strong><br /><small className="text-muted">{product.item_name}</small></td><td>{product.category}</td><td className="text-end">₹{product.current_price.toLocaleString("en-IN")}</td><td className="text-end"><span className={product.stock === 0 ? "badge text-bg-danger" : "badge text-bg-warning"}>{product.stock}</span></td><td><Link to={`/admin/products/edit/${product.id}`} className="btn btn-sm btn-outline-dark">Update stock</Link></td></tr>)}</tbody></table></div></div></main>;
};
export default AdminInventory;
