import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { adminFetch } from "../utils/adminApi";

const statusNames = ["", "PLACED", "CONFIRMED", "PROCESSING", "SHIPPED", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELLED", "RETURN_REQUESTED", "RETURNED", "REFUNDED"];
const transitions = { PLACED: "CONFIRMED", CONFIRMED: "PROCESSING", PROCESSING: "SHIPPED", SHIPPED: "OUT_FOR_DELIVERY", OUT_FOR_DELIVERY: "DELIVERED", DELIVERED: "RETURN_REQUESTED", RETURN_REQUESTED: "RETURNED", RETURNED: "REFUNDED" };
const label = (value) => String(value || "").replaceAll("_", " ");

const AdminOrders = () => {
  const [orders, setOrders] = useState([]); const [status, setStatus] = useState(""); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [pagination, setPagination] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { try { setLoading(true); setError(""); const query = new URLSearchParams({ page: String(page), limit: "20" }); if (status) query.set("status", status); if (search.trim()) query.set("search", search.trim()); const response = await adminFetch(`/admin/orders?${query}`); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to load orders."); setOrders(data.orders || []); setPagination(data.pagination); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  useEffect(() => {
    const loadInitialOrders = async () => {
      try { setLoading(true); setError(""); const query = new URLSearchParams({ page: String(page), limit: "20" }); if (status) query.set("status", status); const response = await adminFetch(`/admin/orders?${query}`); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to load orders."); setOrders(data.orders || []); setPagination(data.pagination); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); }
    };
    loadInitialOrders();
  }, [page, status]);
  const update = async (order, orderStatus) => { try { const response = await adminFetch(`/admin/orders/${order._id}/status`, { method: "PUT", body: JSON.stringify({ orderStatus }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to update order."); setOrders((current) => current.map((item) => item._id === order._id ? { ...item, ...data.order } : item)); } catch (requestError) { setError(requestError.message); } };
  return <main className="container-fluid py-5 px-4"><div className="d-flex justify-content-between align-items-center mb-4"><div><p className="text-muted mb-1">Admin operations</p><h1 className="h2 fw-bold mb-0">Orders</h1></div><Link to="/admin" className="btn btn-outline-dark">Dashboard</Link></div><div className="row g-2 mb-3"><div className="col-md-5"><input className="form-control" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Order number, name, or mobile" /></div><div className="col-md-3"><select className="form-select" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}>{statusNames.map((item) => <option value={item} key={item}>{item ? label(item) : "All statuses"}</option>)}</select></div><div className="col-md-auto"><button className="btn btn-dark" onClick={() => { setPage(1); load(); }}>Search</button></div></div>{error && <div className="alert alert-danger">{error}</div>}<div className="card border-0 shadow-sm"><div className="table-responsive"><table className="table table-hover align-middle mb-0"><thead className="table-dark"><tr><th>Order</th><th>Customer</th><th>Items</th><th>Amount</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading ? <tr><td colSpan="7" className="text-center py-5">Loading orders...</td></tr> : orders.length === 0 ? <tr><td colSpan="7" className="text-center py-5">No orders found.</td></tr> : orders.map((order) => <tr key={order._id}><td><strong>{order.orderNumber}</strong><br /><small className="text-muted">{new Date(order.createdAt).toLocaleDateString("en-IN")}</small></td><td>{order.user?.name || "Deleted user"}<br /><small className="text-muted">{order.user?.email}</small></td><td>{order.items.reduce((total, item) => total + item.quantity, 0)}</td><td>₹{order.totalAmount.toLocaleString("en-IN")}</td><td><span className="badge text-bg-light">{order.paymentStatus}</span></td><td><span className="badge text-bg-secondary">{label(order.orderStatus)}</span></td><td><div className="d-flex flex-column gap-1">{transitions[order.orderStatus] && <button className="btn btn-sm btn-dark" onClick={() => update(order, transitions[order.orderStatus])}>{label(transitions[order.orderStatus])}</button>}{["PLACED", "CONFIRMED", "PROCESSING"].includes(order.orderStatus) && <button className="btn btn-sm btn-outline-danger" onClick={() => update(order, "CANCELLED")}>Cancel</button>}</div></td></tr>)}</tbody></table></div></div>{pagination?.totalPages > 1 && <div className="d-flex justify-content-center align-items-center gap-3 mt-4"><button className="btn btn-outline-dark" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {pagination.page} of {pagination.totalPages}</span><button className="btn btn-outline-dark" disabled={page === pagination.totalPages} onClick={() => setPage(page + 1)}>Next</button></div>}</main>;
};
export default AdminOrders;
